import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const outFit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Momagic Bangladesh Limited",
  description: "Generated by momagic bd",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outFit.variable}`}>
        {children}
      </body>
    </html>
  );
}
